version: '3'
services:
  mq:
    image: redis:6.2.1
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
  db:
    image: postgres:13
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: poc
    volumes:
      - postgres-db:/var/lib/postgresql/data
  web:
    build: .
    command: ["/usr/wait-for-it.sh", "db:5432", "--", "python3", "manage.py", "runserver", "0.0.0.0:8000"]   
    volumes:
      - ./backend:/code/backend
    ports:
      - "8000:8000"
    depends_on:
      - db
      - mq
    restart: always
  celery: 
    build: .
    command: celery -A xxx_api worker -l info
    volumes:
      - ./backend:/code/backend
    depends_on:
      - db
      - mq
      - web
    restart: always
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8080:8080"
volumes:
  postgres-db:
    driver: local
  redis-data:
    driver: local