# Generated by Django 3.1.7 on 2021-03-20 13:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_celery_results', '0008_chordcounter'),
    ]

    operations = [
        migrations.CreateModel(
            name='BinaryResource',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('c619c2b3-b0b9-49a1-ba84-3a4933075573'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('extension', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('url', models.URLField(blank=True, null=True)),
                ('binary_data', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='ParseResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, max_length=2000, null=True)),
                ('body', models.CharField(blank=True, max_length=10000, null=True)),
                ('url', models.URLField(null=True)),
                ('table', models.CharField(blank=True, max_length=100, null=True)),
                ('column0001', models.CharField(blank=True, max_length=1000, null=True)),
                ('column0002', models.CharField(blank=True, max_length=1000, null=True)),
                ('column0003', models.CharField(blank=True, max_length=1000, null=True)),
                ('column0004', models.CharField(blank=True, max_length=1000, null=True)),
                ('column0005', models.CharField(blank=True, max_length=1000, null=True)),
                ('column0006', models.CharField(blank=True, max_length=1000, null=True)),
                ('column0007', models.CharField(blank=True, max_length=1000, null=True)),
                ('column0008', models.CharField(blank=True, max_length=1000, null=True)),
                ('column0009', models.CharField(blank=True, max_length=1000, null=True)),
                ('column0010', models.CharField(blank=True, max_length=1000, null=True)),
                ('column0011', models.CharField(blank=True, max_length=1000, null=True)),
                ('column0012', models.CharField(blank=True, max_length=1000, null=True)),
                ('column0013', models.CharField(blank=True, max_length=1000, null=True)),
                ('column0014', models.CharField(blank=True, max_length=1000, null=True)),
                ('column0015', models.CharField(blank=True, max_length=1000, null=True)),
                ('column0016', models.CharField(blank=True, max_length=1000, null=True)),
                ('column0017', models.CharField(blank=True, max_length=1000, null=True)),
                ('column0018', models.CharField(blank=True, max_length=1000, null=True)),
                ('column0019', models.CharField(blank=True, max_length=1000, null=True)),
                ('column0020', models.CharField(blank=True, max_length=1000, null=True)),
                ('mq_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_celery_results.taskresult')),
            ],
        ),
    ]
