# Generated by Django 3.1.7 on 2021-03-20 13:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_results', '0008_chordcounter'),
        ('xxx_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binaryresource',
            name='id',
            field=models.UUIDField(default=uuid.UUID('877f3c48-2c72-47d5-8134-bac36947506e'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='parseresult',
            name='mq_info',
            field=models.ForeignKey(db_column='mq_task_id', on_delete=django.db.models.deletion.CASCADE, to='django_celery_results.taskresult', to_field='task_id'),
        ),
    ]
