# Generated by Django 3.1.7 on 2021-05-06 14:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('xxx_api', '0005_add_datetime_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binaryresource',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
